### ISSUE TITLE
Cannot build on Ubuntu 16.04

### ISSUE THREAD

**Issue by ThatOneGamer999** [Raymo111/i3lock-color#82]
Running "autoreconf -i && ./configure && make" results in a fatal error:
`../../i3lock-color/i3lock.c:31:31: fatal error: security/pam_appl.h: No such file or directory`

**Comment by PandorasFox** [comment]
#76

**Comment by mrpandey** [comment]
I run Xubuntu 19.04 and ran into the same problem. Installing `libpam0g-dev` solved the issue.
