### ISSUE TITLE
Failed to build on Ubuntu 21.10 - JCS-EXT-BGRA undeclared

### ISSUE THREAD

**Issue by kerruba-milkman** [Raymo111/i3lock-color#261]
## This issue is a....
<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior
Unable to build latest commit on master on ubuntu 21.10 due to an error during compilation:
```
make[1]: Entering directory '<...>/i3lock-color/build'
  CC       i3lock-blur.o
  CC       i3lock-blur_simd.o
  CC       i3lock-dpi.o
  CC       i3lock-jpg.o
../../i3lock-color/jpg.c: In function ‘read_JPEG_file’:
../../i3lock-color/jpg.c:70:29: error: ‘JCS_EXT_BGRA’ undeclared (first use in this function)
   70 |     cinfo.out_color_space = JCS_EXT_BGRA;
      |                             ^~~~~~~~~~~~
../../i3lock-color/jpg.c:70:29: note: each undeclared identifier is reported only once for each function it appears in
```

## Expected Behavior
Build succeed without any issue

## Reproduction Instructions

- I've updated the repository to the latest commit 
- I've installed all the dependencies as described in the documentation
- I've followed the further instructions for building on Debian - https://github.com/Raymo111/i3lock-color/issues/211#issuecomment-809891727

**NOTE: By commenting the line, the application is able to build correctly**

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.13.c.4-34-gd846e7c (2022-03-18) © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2021 Raymond Li
</pre>

Output of `lsb_release`:
```
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish
```

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[x] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by kerruba-milkman** [comment]
As I've already added to the comment, commenting the line unlock the build.
Could it be that some dependency is missing? `libjpeg-turbo` has to be included?

**Comment by Raymo111** [comment]
Have you tried installing the libjpeg-turbo package? Does it work after you do that?
